default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: visu_movies_development

test:
  <<: *default
  database: visu_movies_test

production:
  <<: *default
  database: visu_movies_production
  username: visu_movies
  password: <%= ENV['VISU_MOVIES_DATABASE_PASSWORD'] %>
